// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlstAgUi8L6QVN1zwLkuywTL9bgzs8swo',
    appId: '1:799517854554:web:d4f6cafe11881156090163',
    messagingSenderId: '799517854554',
    projectId: 'teachizlearning',
    authDomain: 'teachizlearning.firebaseapp.com',
    storageBucket: 'teachizlearning.appspot.com',
    measurementId: 'G-JHM3TJMNW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJT-HjFnhY-YS34tnY2YsVFQ9yBYW8XK8',
    appId: '1:799517854554:android:1ba03fb50e0f88d3090163',
    messagingSenderId: '799517854554',
    projectId: 'teachizlearning',
    storageBucket: 'teachizlearning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSLZdnTWecVTREKrJxkP2RyQ2T6VEihQ',
    appId: '1:799517854554:ios:25bee70c3a0d2a0e090163',
    messagingSenderId: '799517854554',
    projectId: 'teachizlearning',
    storageBucket: 'teachizlearning.appspot.com',
    iosClientId: '799517854554-375kjhk6tbi6nudnhs04avrvib6k4ukb.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRSLZdnTWecVTREKrJxkP2RyQ2T6VEihQ',
    appId: '1:799517854554:ios:2f3fa707ab4fa261090163',
    messagingSenderId: '799517854554',
    projectId: 'teachizlearning',
    storageBucket: 'teachizlearning.appspot.com',
    iosClientId: '799517854554-nhj1vlgmef6jijln21leofr35gub1o1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachiz.RunnerTests',
  );
}
